name: java cox fp with maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: mvn package
    - uses: actions/upload-artifact@v1
      with:
        name: java-cox-fp-1.0-SNAPSHOT.jar
        path: java-cox-fp/target/java-cox-fp-1.0-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
        name: java-cox-fp-1.0-SNAPSHOT.jar
        path: artifacts/
    - run: ls artifacts/java-cox-fp-1.0-SNAPSHOT.jar
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Deploy app jar to S3 bucket
      run: aws s3 sync artifacts/ s3://bbkvnaras01/libs/
